name: modulAbdad

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Matrix API
        run: |
          go build -o matrix-api .

      - name: Deploy binary
        run: |
          sudo cp matrix-api /opt/matrix-api/matrix-api
          sudo chmod +x /opt/matrix-api/matrix-api

      - name: Restart Matrix API
        run: |
          sudo systemctl restart matrix-api

      - name: Check Matrix API
        run: |
          sudo systemctl is-active matrix-api